export {default as addMessage} from './addMessage';
export {default as getAllDialogs} from './getAllDialogs';
export {default as getCurrentDialog} from './getCurrentDialog';
export {default as postUser} from './postUser';
export {default as getGeneralChatLink} from './getGeneralChatLink';
export {default as getCurrentUser} from './getCurrentUser';
export {default as addChatToUser} from './addChatToUser';
export {default as addChatToDatabase} from './addChatToDatabase';
export {default as changeLastChatMessage} from './changeLastChatMessage';